# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.1'

services:

  water-grant-shell:
    build:
      context: .
      dockerfile: ./shell/Dockerfile
    image: sawtooth-water-grant-shell
    container_name: water-grant-shell
    volumes:
      - .:/project/sawtooth-water-grant
      - /project/sawtooth-water-grant/sprinkle_app/node_modules
    command: |
      bash -c "
        water-grant-protogen
        cd sprinkle_app/
        npm run build
        cd ../
        tail -f /dev/null
      "

  water-grant-tp:
    build:
        context: .
        dockerfile: ./processor/Dockerfile
    image: sawtooth-water-grant-tp
    container_name: water-grant-tp
    volumes:
      - '.:/project/sawtooth-water-grant'
    depends_on:
      - water-grant-shell
    command: |
      bash -c "
        sleep 1
        water-grant-tp -v -C tcp://validator:4004
      "

  water-grant-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
    image: sawtooth-water-grant-rest-api
    container_name: water-grant-rest-api
    volumes:
      - .:/project/sawtooth-water-grant
    ports:
      - '8000:8000'
    depends_on:
      - water-grant-shell
    command: |
      bash -c "
        chmod -R 777 /project/sawtooth-water-grant &&
        water-grant-rest-api --db-host postgres -vv -B water-grant-rest-api:8000 -C validator:4004
      "

  water-grant-subscriber:
    build:
      context: .
      dockerfile: ./subscriber/Dockerfile
    image: sawtooth-water-grant-subscriber
    container_name: water-grant-subscriber
    volumes:
      - '.:/project/sawtooth-water-grant'
    depends_on:
      - water-grant-shell
      - postgres
    command: |
      bash -c "
        chmod -R 777 /project/sawtooth-water-grant &&
        water-grant-subscriber subscribe --db-host postgres -vv -C tcp://validator:4004
      "

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.2
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.2
    container_name: sawtooth-rest-api-default
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008

  validator:
    image: hyperledger/sawtooth-validator:1.2
    container_name: sawtooth-validator-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:1.2
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust -C tcp://validator:5050

  postgres:
    image: postgres:alpine
    container_name: water-grant-postgres
    restart: always
    environment:
      POSTGRES_USER: sawtooth
      POSTGRES_PASSWORD: sawtooth
      POSTGRES_DB: water-grant
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: water-grant-adminer
    restart: always
    ports:
      - '8080:8080'

  sprinkle-app:
    build: ./sprinkle_app
    image: water-grant-sprinkle-app
    container_name: sprinkle-app
    volumes:
      - ./sprinkle_app/public/:/usr/local/apache2/htdocs/
    expose:
      - 80
    ports:
      - '8040:80'
    depends_on:
      - water-grant-shell
      - water-grant-rest-api
