# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: water_grant_protobuf/payload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"water_grant_protobuf/payload.proto\"\xf3\x02\n\x07Payload\x12\x1f\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0f.Payload.Action\x12(\n\x0c\x63reate_admin\x18\x02 \x01(\x0b\x32\x12.CreateAdminAction\x12&\n\x0b\x63reate_user\x18\x03 \x01(\x0b\x32\x11.CreateUserAction\x12&\n\x0bupdate_user\x18\x04 \x01(\x0b\x32\x11.UpdateUserAction\x12*\n\rcreate_sensor\x18\x05 \x01(\x0b\x32\x13.CreateSensorAction\x12*\n\rupdate_sensor\x18\x06 \x01(\x0b\x32\x13.UpdateSensorAction\x12\x11\n\ttimestamp\x18\x07 \x01(\x04\"b\n\x06\x41\x63tion\x12\x10\n\x0c\x43REATE_ADMIN\x10\x00\x12\x0f\n\x0b\x43REATE_USER\x10\x01\x12\x0f\n\x0bUPDATE_USER\x10\x02\x12\x11\n\rCREATE_SENSOR\x10\x03\x12\x11\n\rUPDATE_SENSOR\x10\x04\"!\n\x11\x43reateAdminAction\x12\x0c\n\x04name\x18\x01 \x01(\t\"T\n\x10\x43reateUserAction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05quota\x18\x02 \x01(\x01\x12#\n\x1b\x63reated_by_admin_public_key\x18\x03 \x01(\t\"_\n\x10UpdateUserAction\x12\x17\n\x0fuser_public_key\x18\x01 \x01(\t\x12\r\n\x05quota\x18\x02 \x01(\x01\x12#\n\x1bupdated_by_admin_public_key\x18\x03 \x01(\t\"a\n\x12\x43reateSensorAction\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x12\x12\x11\n\tlongitude\x18\x03 \x01(\x12\x12\x13\n\x0bmeasurement\x18\x04 \x01(\x01\"<\n\x12UpdateSensorAction\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x13\n\x0bmeasurement\x18\x02 \x01(\x01\x62\x06proto3')



_PAYLOAD = DESCRIPTOR.message_types_by_name['Payload']
_CREATEADMINACTION = DESCRIPTOR.message_types_by_name['CreateAdminAction']
_CREATEUSERACTION = DESCRIPTOR.message_types_by_name['CreateUserAction']
_UPDATEUSERACTION = DESCRIPTOR.message_types_by_name['UpdateUserAction']
_CREATESENSORACTION = DESCRIPTOR.message_types_by_name['CreateSensorAction']
_UPDATESENSORACTION = DESCRIPTOR.message_types_by_name['UpdateSensorAction']
_PAYLOAD_ACTION = _PAYLOAD.enum_types_by_name['Action']
Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOAD,
  '__module__' : 'water_grant_protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:Payload)
  })
_sym_db.RegisterMessage(Payload)

CreateAdminAction = _reflection.GeneratedProtocolMessageType('CreateAdminAction', (_message.Message,), {
  'DESCRIPTOR' : _CREATEADMINACTION,
  '__module__' : 'water_grant_protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateAdminAction)
  })
_sym_db.RegisterMessage(CreateAdminAction)

CreateUserAction = _reflection.GeneratedProtocolMessageType('CreateUserAction', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERACTION,
  '__module__' : 'water_grant_protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateUserAction)
  })
_sym_db.RegisterMessage(CreateUserAction)

UpdateUserAction = _reflection.GeneratedProtocolMessageType('UpdateUserAction', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERACTION,
  '__module__' : 'water_grant_protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:UpdateUserAction)
  })
_sym_db.RegisterMessage(UpdateUserAction)

CreateSensorAction = _reflection.GeneratedProtocolMessageType('CreateSensorAction', (_message.Message,), {
  'DESCRIPTOR' : _CREATESENSORACTION,
  '__module__' : 'water_grant_protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateSensorAction)
  })
_sym_db.RegisterMessage(CreateSensorAction)

UpdateSensorAction = _reflection.GeneratedProtocolMessageType('UpdateSensorAction', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESENSORACTION,
  '__module__' : 'water_grant_protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:UpdateSensorAction)
  })
_sym_db.RegisterMessage(UpdateSensorAction)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAYLOAD._serialized_start=39
  _PAYLOAD._serialized_end=410
  _PAYLOAD_ACTION._serialized_start=312
  _PAYLOAD_ACTION._serialized_end=410
  _CREATEADMINACTION._serialized_start=412
  _CREATEADMINACTION._serialized_end=445
  _CREATEUSERACTION._serialized_start=447
  _CREATEUSERACTION._serialized_end=531
  _UPDATEUSERACTION._serialized_start=533
  _UPDATEUSERACTION._serialized_end=628
  _CREATESENSORACTION._serialized_start=630
  _CREATESENSORACTION._serialized_end=727
  _UPDATESENSORACTION._serialized_start=729
  _UPDATESENSORACTION._serialized_end=789
# @@protoc_insertion_point(module_scope)
